"""Add ticket rating and HR management fields

Revision ID: 283d19e25a85
Revises: add_payment_reminders_and_service_orders
Create Date: 2025-09-30 22:07:33.473148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '283d19e25a85'
down_revision = 'add_payment_reminders_and_service_orders'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entry',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=200), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('entry_date', sa.DateTime(), nullable=False),
                    sa.Column('category', sa.String(length=50), nullable=True),
                    sa.Column('priority', sa.String(length=50), nullable=True),
                    sa.Column('status', sa.String(length=50), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('hours_worked', sa.Float(), nullable=True),
                    sa.Column('location', sa.String(
                        length=200), nullable=True),
                    sa.Column('tags', sa.Text(), nullable=True),
                    sa.Column('attachments', sa.JSON(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('system_backup',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('backup_type', sa.String(
                        length=50), nullable=False),
                    sa.Column('file_path', sa.String(
                        length=500), nullable=True),
                    sa.Column('file_size', sa.BigInteger(), nullable=True),
                    sa.Column('status', sa.String(length=50), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('completed_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('system_notification',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=200), nullable=False),
                    sa.Column('message', sa.Text(), nullable=False),
                    sa.Column('notification_type', sa.String(
                        length=50), nullable=True),
                    sa.Column('is_read', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('expires_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('matrix_history',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('matrix_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('action', sa.String(length=50), nullable=False),
                    sa.Column('changes', sa.JSON(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['matrix_id'], ['matrix.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column('rating_comment', sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column('rated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rated_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_ticket_rated_by', 'user', ['rated_by'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(
            sa.Column('is_suspended', sa.Boolean(), nullable=True, default=False))
        batch_op.add_column(
            sa.Column('suspension_reason', sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column('suspended_by', sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column('suspended_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_user_suspended_by', 'user', [
                                    'suspended_by'], ['id'])

    # Migrar datos de password a password_hash
    op.execute(
        "UPDATE user SET password_hash = password WHERE password_hash IS NULL")
    op.execute("UPDATE user SET is_suspended = false WHERE is_suspended IS NULL")

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('password', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint('fk_user_suspended_by', type_='foreignkey')
        batch_op.drop_column('suspended_at')
        batch_op.drop_column('suspended_by')
        batch_op.drop_column('suspension_reason')
        batch_op.drop_column('is_suspended')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ticket_rated_by', type_='foreignkey')
        batch_op.drop_column('rated_by')
        batch_op.drop_column('rated_at')
        batch_op.drop_column('rating_comment')
        batch_op.drop_column('rating')

    op.drop_table('matrix_history')
    op.drop_table('system_notification')
    op.drop_table('system_backup')
    op.drop_table('journal_entry')
    # ### end Alembic commands ###
