"""Add username field and make email optional

Revision ID: add_username_field
Revises: 26944fc49940
Create Date: 2025-10-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_username_field'
down_revision = '26944fc49940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Agregar campo username (temporal nullable para permitir migración)
        batch_op.add_column(
            sa.Column('username', sa.String(length=50), nullable=True))
        batch_op.add_column(
            sa.Column('full_name', sa.String(length=100), nullable=True))

        # Hacer email opcional
        batch_op.alter_column('email',
                              existing_type=sa.VARCHAR(length=120),
                              nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
                              existing_type=sa.VARCHAR(length=120),
                              nullable=False)
        batch_op.drop_column('full_name')
        batch_op.drop_column('username')
    # ### end Alembic commands ###
